//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

public partial class AssignmentModelEntities : ObjectContext
{
    public const string ConnectionString = "name=AssignmentModelEntities";
    public const string ContainerName = "AssignmentModelEntities";

    #region Constructors

    public AssignmentModelEntities()
        : base(ConnectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public AssignmentModelEntities(string connectionString)
        : base(connectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public AssignmentModelEntities(EntityConnection connection)
        : base(connection, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    #endregion

    #region ObjectSet Properties

    public ObjectSet<ict_Course> ict_Course
    {
        get { return _ict_Course  ?? (_ict_Course = CreateObjectSet<ict_Course>("ict_Course")); }
    }
    private ObjectSet<ict_Course> _ict_Course;

    public ObjectSet<ict_Degree> ict_Degree
    {
        get { return _ict_Degree  ?? (_ict_Degree = CreateObjectSet<ict_Degree>("ict_Degree")); }
    }
    private ObjectSet<ict_Degree> _ict_Degree;

    public ObjectSet<ict_Diploma> ict_Diploma
    {
        get { return _ict_Diploma  ?? (_ict_Diploma = CreateObjectSet<ict_Diploma>("ict_Diploma")); }
    }
    private ObjectSet<ict_Diploma> _ict_Diploma;

    public ObjectSet<ict_Feedback> ict_Feedback
    {
        get { return _ict_Feedback  ?? (_ict_Feedback = CreateObjectSet<ict_Feedback>("ict_Feedback")); }
    }
    private ObjectSet<ict_Feedback> _ict_Feedback;

    public ObjectSet<ict_Graduate> ict_Graduate
    {
        get { return _ict_Graduate  ?? (_ict_Graduate = CreateObjectSet<ict_Graduate>("ict_Graduate")); }
    }
    private ObjectSet<ict_Graduate> _ict_Graduate;

    public ObjectSet<ict_Program> ict_Program
    {
        get { return _ict_Program  ?? (_ict_Program = CreateObjectSet<ict_Program>("ict_Program")); }
    }
    private ObjectSet<ict_Program> _ict_Program;

    public ObjectSet<ict_ProgramOverview> ict_ProgramOverview
    {
        get { return _ict_ProgramOverview  ?? (_ict_ProgramOverview = CreateObjectSet<ict_ProgramOverview>("ict_ProgramOverview")); }
    }
    private ObjectSet<ict_ProgramOverview> _ict_ProgramOverview;

    public ObjectSet<ict_Staff> ict_Staff
    {
        get { return _ict_Staff  ?? (_ict_Staff = CreateObjectSet<ict_Staff>("ict_Staff")); }
    }
    private ObjectSet<ict_Staff> _ict_Staff;

    public ObjectSet<ict_Student> ict_Student
    {
        get { return _ict_Student  ?? (_ict_Student = CreateObjectSet<ict_Student>("ict_Student")); }
    }
    private ObjectSet<ict_Student> _ict_Student;

    public ObjectSet<ictMedia> ictMedias
    {
        get { return _ictMedias  ?? (_ictMedias = CreateObjectSet<ictMedia>("ictMedias")); }
    }
    private ObjectSet<ictMedia> _ictMedias;

    public ObjectSet<ictPage> ictPages
    {
        get { return _ictPages  ?? (_ictPages = CreateObjectSet<ictPage>("ictPages")); }
    }
    private ObjectSet<ictPage> _ictPages;

    #endregion
}
